#  =========== les infos de la connexion à la bdd

jdbc.url=jdbc:mysql://localhost:3306/db_projet_ecommerce?createDatabaseIfNotExist=true

jdbc.driver=com.mysql.cj.jdbc.Driver

jdbc.user=root

jdbc.mdp=root



#  ============ Propriété de hibernate
hb.dialect=org.hibernate.dialect.MySQL5Dialect

hb.strategy=update

hb.sql=true